services:
  backend:
    build:
      context: ./be
      target: production
    container_name: nest_app_prod
    ports:
      - "3001:3001"
    environment:
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SYNCHRONIZE: "false"
    command: >
      sh -c "echo 'CLERK_SECRET_KEY=$CLERK_SECRET_KEY
      DB_HOST=$DB_HOST
      DB_PORT=$DB_PORT
      DB_USERNAME=$DB_USERNAME
      DB_PASSWORD=$DB_PASSWORD
      DB_NAME=$DB_NAME
      DB_SYNCHRONIZE=$DB_SYNCHRONIZE' > .env"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      target: runner
    container_name: next_app_prod
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: /dashboard
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    command: >
      sh -c "echo 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
      CLERK_SECRET_KEY=$CLERK_SECRET_KEY
      NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL
      NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
      NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL' > .env.production"
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres_db_prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data_prod:

networks:
  app-network:
    driver: bridge
