apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: modern-fullstack-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: azazahamed/modern-fullstack-boilerplate:frontend-latest
          ports:
            - containerPort: 3000
