# Development stage
FROM node:22-alpine3.19 AS development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build # Ensure the build script generates the dist folder
CMD ["npm", "run", "start:dev"]

# Production stage
FROM node:22-alpine3.19 AS production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
COPY --from=development /usr/src/app/dist ./dist
CMD ["node", "dist/main"]
