apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: modern-fullstack-boilerplate
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
